spring:
  application:
    name: s31719
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always